ENH: add minimum_bounding_circle
pygeos/pygeos pull request #315
Opened 2021-03-16 13:47 UTC by martinfleis

Exposing `GEOSMinimumBoundingCircle_r`. 

xref #126

2021-03-16 13:50 UTC, martinfleis commented
Hmm, this seems to work only on macOS and segfaults elsewhere. I am afraid that is out of my C capabilities to debug this.

2021-03-16 14:00 UTC, jorisvandenbossche commented
GEOSMinimumBoundingCircle_r takes an additional (`radius`) argument that is missing here? (not sure why it would sometimes succeed then, if that's the case)

2021-03-16 14:03 UTC, jorisvandenbossche commented
Ah, so it's not an additional "argument" to the function in a python-sense, but it actually is an additional return value (I wanted to say: have a look at the "Yd_Y" signatures, but so that won't work either)

2021-03-16 15:18 UTC, jorisvandenbossche commented
Using the following wrapper around the actual GEOS function to align the signature avoids the segfault for me on linux:

```
static void* GEOSMinimumBoundingCircleWithReturn(void* context, void* geom) {
  GEOSGeometry* center = NULL;
  double radius;
  void* ret = GEOSMinimumBoundingCircle_r(context, geom, &radius, &center);
  if (ret == NULL) {
    return NULL;
  }
  GEOSGeom_destroy_r(context, center);
  return ret;
}
static void* minimum_bounding_circle_data[1] = {GEOSMinimumBoundingCircleWithReturn};
```

Now, of course, that simply ignores the additional center/radius results. 

If we want to add those to the actual python return value, we need to think about the desired API for this (different return values? a tuple of arrays or an array of tuples?) I have done something similar for `polygonize_full` in https://github.com/pygeos/pygeos/pull/298

2021-03-16 15:26 UTC, jorisvandenbossche commented
PostGIS has a separate [`ST_MinimumBoundingRadius`](https://postgis.net/docs/ST_MinimumBoundingRadius.html), so [`ST_MinimumBoundingCircle`](https://postgis.net/docs/ST_MinimumBoundingCircle.html) only returns the geometry (which I think I like, since often you might want one or the other?)

2021-03-16 15:40 UTC, martinfleis commented
Thanks a lot for the wrapper!

> PostGIS has a separate ST_MinimumBoundingRadius, so ST_MinimumBoundingCircle only returns the geometry (which I think I like, since often you might want one or the other?)

I also like this approach. It feels natural to get a polygon from `minimum_bounding_circle`. We can do the same here and then mirror this behaviour for `maximum_inscribed_circle` (which I am also playing with now) which returns a LineString from the centre to a point on the boundary.

2021-04-02 15:03 UTC, caspervdw requested changes
Thanks @martinfleis , some small comments, maybe you can also add the `radius` version?

2021-04-02 15:03 UTC, caspervdw commented on src/ufuncs.c
> +static void* GEOSMinimumBoundingCircleWithReturn(void* context, void* geom) {
We could also have the `Y_d` function that returns the radius `minimum_bounding_radius` with this wrapper:

```
static int GEOSMinimumBoundingRadius(void* context, GEOSGeometry* geom, double* radius) {
  GEOSGeometry* center = NULL;
  GEOSGeometry* ret = GEOSMinimumBoundingCircle_r(context, geom, radius, &center);
  if (ret == NULL) {
    return 0;  // exception code
  }
  GEOSGeom_destroy_r(context, center);
  GEOSGeom_destroy_r(context, ret);
  return 1;  // success code
}
```

2021-04-02 15:03 UTC, caspervdw commented on src/ufuncs.c
> +  void* ret = GEOSMinimumBoundingCircle_r(context, geom, &radius, &center);
```suggestion
  GEOSGeometry* ret = GEOSMinimumBoundingCircle_r(context, geom, &radius, &center);
```

2021-04-02 15:03 UTC, caspervdw commented on pygeos/constructive.py
> +    <pygeos.Geometry POLYGON EMPTY>
Thanks; same comment as the other PR, can you include these as unittests as well?

2021-04-02 19:02 UTC, jorisvandenbossche commented on pygeos/measurement.py
> +
Same here for `**kwargs`

2021-04-02 19:02 UTC, jorisvandenbossche commented on pygeos/measurement.py
> +    """Computes the radius of tje minimum bounding circle that encloses an input geometry.
```suggestion
    """Computes the radius of the minimum bounding circle that encloses an input geometry.
```

2021-04-02 19:02 UTC, jorisvandenbossche commented on src/ufuncs.c
> +static int GEOSMinimumBoundingRadius(void* context, GEOSGeometry* geom, double* radius) {
Can you move this to where the other Y_d functions are defined? (this is the Y_Y section)

2021-04-03 12:15 UTC, caspervdw approved these changes
Thanks! All looks good now for merge. Can you add a line to the CHANGELOG under "added GEOS functions" ?

2021-04-03 13:05 UTC, martinfleis commented
> Can you add a line to the CHANGELOG under "added GEOS functions" ?

@caspervdw All done. Thanks for the review to both of you.

2021-04-03 18:01 UTC, merged