Raise warning and return None on invalid WKB instead of raising exception
pygeos/pygeos pull request #321
Opened 2021-03-18 00:41 UTC by brendan-ward

Resolves #320

For reasons stated in #320, it is problematic to raise exceptions when deserializing invalid geometries from formats such as WKB.  This provides a way to gracefully read those in, raise a warning, and allow the user to filter them out instead of failing hard.

This adds a new enum value `PGWARN_GEOS_EXCEPTION` which is used to raise the GEOS exception as a warning instead of an exception.

2021-03-18 14:27 UTC, jorisvandenbossche commented on src/geos.h
> +      PyErr_WarnEx(PyExc_Warning, last_error, 0);                                        \
We should probably prepend that last_error message to make the warning message clearer? (saying something about some values being invalid WKB and being replaced with None in the result)

2021-03-23 21:20 UTC, brendan-ward commented
A couple things to consider:
* I'm not sure that `ignore_invalid` is the best name for this parameter.  Is there something better?
* WKT and WKB warning types are separate enum values now but this doesn't add much value.  These could be combined into a single enum value if we don't think these need to be kept separate.

2021-03-25 18:59 UTC, caspervdw requested changes
This looks good. Some thoughts about the keyword `ignore_invalid`:

I think it should be a string (like numpy does in `np.seterr` or pandas in `to_datetime`). In that way we can later on add more functionality without breaking the API. This can be done now easily by only allowing `raise` and `ignore`, and converting that to a bool to pass into the `lib.from_wkt`. Then our external API remains extensible. Then it is reasonable to rename it to:

- `errors` (like in pandas.to_datetime https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html
- `on_invalid`

The separation between WKT and WKB warnings is not necessary, but I am also not against it. We can always change it back.

2021-03-26 09:50 UTC, jorisvandenbossche commented
+1 on making it a string option

> This can be done now easily by only allowing `raise` and `ignore`

We could maybe also further use the terminology of `np.seterr` and use "raise" and "warn", which keeps the possibility open to add a "ignore" (which would not show the warning)? 

About naming, I think I find `on_invalid` a bit more descriptive than `errors`.

2021-03-29 20:11 UTC, brendan-ward commented
Latest changes make this a string parameter and add an `ignore` option.

2021-03-31 18:04 UTC, caspervdw approved these changes
Looks good, one nitpick about the docstrings and then good to merge!

2021-03-31 18:04 UTC, caspervdw commented on pygeos/io.py
> +    on_invalid : str, one of {"raise", "warn", "ignore"} (default: "raise")
From https://numpydoc.readthedocs.io/en/latest/format.html:

> When a parameter can only assume one of a fixed set of values, those values can be listed in braces, with the default appearing first:
> order : {'C', 'F', 'A'}
    Description of `order`.

```suggestion
    on_invalid : {"raise", "warn", "ignore"}
```

The default is also listed in the call signature, which is visible in the docs.

Also the markup of the list below is not ok, see https://pygeos--321.org.readthedocs.build/en/321/io.html#pygeos.io.from_wkb. You might want each line with a hyphens (not sure)

2021-03-31 18:25 UTC, jorisvandenbossche commented on pygeos/io.py
> +        ignore: invalid WKT geometries will be returned as `None` without a warning.
```suggestion
        - raise: an exception will be raised if WKT input geometries are invalid.
        - warn: a warning will be raised and invalid WKT geometries will be
          returned as `None`.
        - ignore: invalid WKT geometries will be returned as `None` without a warning.
```

2021-04-01 20:09 UTC, merged